export const IOS_VOICEMAIL_LAYOUT = {
  canvasWidth: 1080,
  canvasHeight: 1920,
  phoneRadius: 86,
  phonePaddingX: 34,
  phonePaddingTop: 28,
  phonePaddingBottom: 30,
  statusTimeFontSize: 36,
  statusTopOffset: 6,
  island: {
    width: 286,
    height: 50,
    topMargin: 8,
    bottomMargin: 34,
  },
  nav: {
    buttonSize: 92,
    iconSize: 32,
    labelFontSize: 20,
    rowBottomMargin: 38,
  },
  profile: {
    size: 176,
    topMargin: -6,
    initialsFontSize: 58,
  },
  namePill: {
    topMargin: 10,
    horizontalPadding: 20,
    verticalPadding: 8,
    fontSize: 52,
  },
  metadata: {
    topMargin: 16,
    fontSize: 38,
  },
  scrubber: {
    topMargin: 56,
    timeFontSize: 41,
    timelineHeight: 10,
    timelineTopMargin: 10,
    knobWidth: 86,
    knobHeight: 44,
    controlsTopMargin: 24,
    controlSize: 62,
    controlGap: 16,
  },
  transcript: {
    topMargin: 64,
    labelFontSize: 43,
    bodyTopMargin: 2,
    bodyFontSize: 50,
  },
  dock: {
    topMargin: 24,
    height: 88,
    searchSize: 88,
    borderRadius: 999,
    fontSize: 30,
    badgeFontSize: 21,
    horizontalPadding: 22,
    searchLeftMargin: 14,
  },
  previewMaxWidth: 390,
  referenceOverlayOpacity: 0.4,
} as const
